- hosts: all
  remote_user: ansibletower
  become: yes
  become_method: sudo
  become_user: root
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    upassword: Cfadmin@1234
    uusername: Cfadmin
  tasks:
  - name: Creating user "{{ uusername }}" with admin access
    user: 
      name: "{{ uusername }}"
      password: "{{ upassword | password_hash('sha512') }}"
     
    
